# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fef079fbf9430084038e3ea7218b292d"
name = "stagin-cross-promotion"
handle = "stagin-cross-promotion"
application_url = "https://spiritual-kills-cope-prague.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ds-demo-plus-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://spiritual-kills-cope-prague.trycloudflare.com/auth/callback",
  "https://spiritual-kills-cope-prague.trycloudflare.com/auth/shopify/callback",
  "https://spiritual-kills-cope-prague.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
